### ISSUE TITLE
This plugin is not displayed on the statusline of gvim

### ISSUE THREAD

**Issue by minchenv** [lambdalisue/battery.vim#15]
I am using battery.vim on windows. When I configure it according to the documentation, battery.vim does not display as expected. What should I do? (I have restarted vim)
![P~___WQD__0NBY_XQ__W77R.png](https://i.loli.net/2021/03/26/t3TgOrqR4X8GnwA.png)

**Comment by lambdalisue** [comment]
If the screenshot is what all you have, the value of `g:lightline` is invalid. Visit https://github.com/itchyny/lightline.vim to get more help.
