### ISSUE TITLE
[feature] When the battey is '0%', don't display the battery in the airline

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/battery.vim#18]
When the desktop don't have a battery, the battery percentage will be '0%'.

```shell
$ acpi
Battery 0: Discharging, 0%, rate information unavailable
```

![image](https://user-images.githubusercontent.com/32936898/141061813-cd8b8330-0d4b-47bd-b86c-4f1d80764950.png)

How can it not be displayed in the airline when the percentage is '0%'?

Thanks!

**Comment by lambdalisue** [comment]
Unfortunately, battery.vim does not have such feature so write Vim script by yourself.
