### ISSUE TITLE
Suggestion: add quick guide on how to add battery to vim-airline

### ISSUE THREAD

**Issue by ramadhanafif** [lambdalisue/battery.vim#19]
Would you mind to add a guide on enabling this on vim-airline? I was frustrated trying to make this work on airline. In case you were asking, I do read the manual for both plugins. I made it work but after some trial and error.

I'm providing my own implementation below:

--------------------------

Add to vimrc(vim)/init.vim(neovim):
```
let g:airline#extensions#battery#enabled = 1

function! AirlineInit()
    let g:airline_section_b = airline#section#create_left(['battery'])
endfunction
autocmd User AirlineAfterInit call AirlineInit()
```

**Comment by 1094** [comment]
I added the following to my config: `let g:airline_section_y = '%{battery#component()}'` and that did the trick.

**Comment by lambdalisue** [comment]
I'm sorry but there are tons of statusline plugin and I don't want to add usage one by one.
I think Wiki is open so please use it (if not, I'll open)

**Comment by ramadhanafif** [comment]
Understandable. Have a good day
