### ISSUE TITLE
How to tell when no battery?

### ISSUE THREAD

**Issue by justinhj** [lambdalisue/battery.vim#20]
Hi, firstly thanks for this great plugin!
I am trying to configure this to not be part of my status line on a desktop which has no battery. Is there a way to detect that? It shows as charging and 100%. I guess I'm wondering if there is a way in the backend to detect there is no battery?

**Comment by lambdalisue** [comment]
Unfortunately, there is no way to detect that in this plugin and I'm not going to add such feature because it's quite depends on the backend.

**Comment by justinhj** [comment]
Thanks for the reply. No problem, I only need it for Windows and I will just add it as a wrapper on my end.
