### ISSUE TITLE
Vim-Airline Integration Bug(?)

### ISSUE THREAD

**Issue by shshshshshan** [lambdalisue/battery.vim#25]
When I install the plugin, just as after installing, the display turns glitchy and unstable. I don't know if this is because of my system. I am using Windows Subsystem for Linux - Ubuntu Distro, Windows 11. I forgot to save a screenshot of my NVIM because I already unregistered the distro and I'm afraid that I will have to reconfigure everything back and install packages from the start to fix the bug.

**Comment by lambdalisue** [comment]
I'm sorry but I have no idea what are you talking about... "When I install the plugin, just as after installing, the display turns glitchy and unstable" explains nothing.

**Comment by shshshshshan** [comment]
I'll try to provide a screenshot next time.
