### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by whisperity** [lambdalisue/battery.vim#7]
Hello!

This plugin sounds amazing. I've read that Linux is not supported. Unfortunately, I can't contribute with a PR because I don't know how to Vimscript... however, I've dug the docs and code for what your plugin might listen to and what the corresponding Linux counterparts are.

On most modern Linux systems, `/sys` is a kernel-backed filesystem where device information can be queried. As per the Unix philosophy, these directories also contain just plain old text files.

The AC power brick is available here: `/sys/class/power_supply/AC` (these directories are all symlinks to "magic" device-ID based locations, such as `../../devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0003:00/AC`...)

```bash
$ cat /sys/class/power_supply/AC/type
Mains
$ cat /sys/class/power_supply/AC/online
1
```

The battery, or batteries, are available under `/sys/class/power_supply/BAT0`, `BAT1`, ...

```bash
$ cat /sys/class/power_supply/BAT0/type
Battery
$ cat /sys/class/power_supply/BAT0/present
1
$ cat /sys/class/power_supply/BAT0/technology
Li-ion
$ cat /sys/class/power_supply/BAT0/alarm
0
$ cat /sys/class/power_supply/BAT0/capacity
95
$ cat /sys/class/power_supply/BAT0/capacity_level
Normal
$ cat /sys/class/power_supply/BAT0/charge_full
4294000
$ cat /sys/class/power_supply/BAT0/charge_full_design
4294000
$ cat /sys/class/power_supply/BAT0/charge_now
4113000
```

I believe the last 3 values are in mA. Unfortunately, some batteries (or ACPI implementations?) might report `energy_full`, `energy_now` and `energy_full_design` instead of `charge_*`, which will be measured in either mWh or Wh.
But I believe simply hooking onto the `capacity` value (expressed as %) should be fine as a presentation to the user. As far as I can see, the graphical widget in KDE does the same.

These value need not be manually updated by a service or a system call. The kernel keeps the value up-to-date, and simply reading the appropriate "system file" gives you the value.

**Comment by lambdalisue** [comment]
Cool. I'll try

**Comment by lambdalisue** [comment]
@whisperity I haven't tried it but could you try #8?

**Comment by Freed-Wu** [comment]
i believe <https://github.com/lambdalisue/battery.vim/pull/12> can
help fix this issue. could anyone help to try it can work in others' linux?
