### ISSUE TITLE
[Feature request] Add support Vim on Android through termux-battery-status

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/battery.vim#9]
i know `termux-battery-status` can return a json about battery status, like this:
```{.json}
{
  "health": "GOOD",
  "percentage": 52,
  "plugged": "UNPLUGGED",
  "status": "NOT_CHARGING",
  "temperature": 31.0,
  "current": 232
}
```

thanks!

**Comment by lambdalisue** [comment]
I've no idea about termux-batter-status. Could you explain it?

**Comment by Freed-Wu** [comment]
![screenshot](https://user-images.githubusercontent.com/32936898/95005424-f7c1d300-062a-11eb-87c0-11e19fde22ea.jpg)

```{.vim}
" termux_battery.vim
function! s:termux_battery() abort " {{{
    if executable('termux-battery-status') " someone need install termux: API to own this program
        let l:content = trim(system('termux-battery-status')) " trim to prevent the trailing non-display characters
        let l:json = webapi#json#decode(l:content) " need <https://github.com/mattn/webapi-vim>
        return get(l:json, 'percentage', -1)
    endif
    return -1
endfunction " }}}
echomsg s:termux_battery()
```

![image](https://user-images.githubusercontent.com/32936898/95005661-1e353d80-062e-11eb-8585-6c6f615dbfdc.png)

![image](https://user-images.githubusercontent.com/32936898/95005657-08277d00-062e-11eb-8699-8f1cca7ff819.png)

it has lost 3% charge:)

**Comment by lambdalisue** [comment]
Well, so what is termux-battery-status?

**Comment by whisperity** [comment]
https://wiki.termux.com/wiki/Main_Page
> Termux is an Android terminal emulator and Linux environment application that works directly with no rooting or setup required.

**Comment by lambdalisue** [comment]
I see. So Vim works on Android and `termux-batery-status` returns the following json

```json
{
  "health": "GOOD",
  "percentage": 52,
  "plugged": "UNPLUGGED",
  "status": "NOT_CHARGING",
  "temperature": 31.0,
  "current": 232
}
```

which `'percentage'` is usable. OK.
